Cleanup.

diff --git a/restartDBs b/restartDBs
--- a/restartDBs
+++ b/restartDBs
@@ -1,20 +1,32 @@
 #!/bin/bash
-exec 3>&1
-exec >&/dev/null
-echo 1>&3 "Stopping kafka"
-kill -9 $(ps -ax | grep -v grep | grep -i kafka | awk '{print $1}')
-echo 1>&3 "Stopping Zookeeper"
+
+#On error, crash and paint the error red
+set -e
+exec 2> >(while read line; do echo -e "\e[01;31m$line\e[0m" >&2; done)
+
+echo "Stopping kafka"
+PIDS=$(ps ax | grep -i 'kafka\.Kafka' | grep java | grep -v grep | awk '{print $1}')
+if [ -n "$PIDS" ]; then
+  kill -SIGTERM $PIDS
+fi
+
+echo "Stopping Zookeeper"
 sudo service zookeeper stop
-echo 1>&3 "Clearing all databases"
-rm -r ~/.ethereumH/*/
-rm ~/.ethereumH/indexOffset
+
+echo "Clearing all databases"
+rm -rf ~/.ethereumH
+mkdir -p ~/.ethereumH/conf/
+cp blockapps-data/*Genesis.json ~/.ethereumH/conf/
 sudo -u postgres dropdb eth
 sudo -u postgres createdb eth
-echo 1>&3 "Starting Zookeeper"
+
+echo "Starting Zookeeper"
 sudo service zookeeper start
 sleep 2
-echo 1>&3 "Starting kafka"
+
+echo "Starting kafka"
 ~/kafka/doit 
 sleep 2
-echo 1>&3 "Initializing the database"
-( cd ../blockapps-data; strato-setup )
+
+echo "Initializing the database"
+strato-setup --genesisBlockName=stablenet
